# Generated by Django 4.2 on 2023-05-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
