# Generated by Django 4.2 on 2023-05-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbook', '0002_alter_userinfomodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
